name: Build and Test Multiple Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
      services: ${{ steps.tejas.outputs.services }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          something: 'something/**'
    - name: asdfasdf
      id: tejas
      run: |
        SERVICES=[]
        SERVICES=${{ steps.filter.outputs.changes }}
        echo $SERVICES
        echo "services=$SERVICES" >> $GITHUB_OUTPUT
    - name: asdfadasdasdf
      run: |
        echo ${{ steps.tejas.outputs.services }}
          
          
  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.services) }}
    steps:
      - name: sasdf
        run: echo "Building and testing${{ matrix.services }}"
        
