name: Build and Test Multiple Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
      services: ${{ steps.tejas.outputs.services }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          something: 'something/**'
    - name: asdfasdf
      id: tejas
      run: |
        sudo apt-get install jq
        SERVICES=$(jq -c 'keys' metadata.json)
        echo "services=$SERVICES" >> $GITHUB_OUTPUT

    - name: asdfadasdasdf
      run: |
        echo ${{ steps.tejas.outputs.services }}
        echo ${{ steps.filter.outputs.changes }}
          
          
  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }} ||  github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        package: ${{ 
          github.event_name == 'workflow_dispatch' && 
          fromJSON(needs.changes.outputs.services) || 
          fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: sasdf
        run: echo "Building and testing${{ matrix.package }}"
        
