name: Run Tests on Multiple Node.js Versions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]  # Matrix will create jobs for each version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        run: echo ${{ matrix.node-version }}
