name: Build and Test Multiple Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
      services: ${{ steps.tejas.outputs.services }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          something: 'something/**'
    - name: asdfasdf
      id: tejas
      run: |
        sudo apt-get install jq
        if [ ${{ steps.filter.outputs.changes }} != '[]' ]; then
            echo "services=${{ fromJSON(steps.filter.outputs.changes) }}" >> $GITHUB_OUTPUT
        else
            SERVICES=$(jq -c 'keys' metadata.json)
            # Set the matrix as an output
            echo "services=$SERVICES" >> $GITHUB_OUTPUT
        fi
          
    - name: asdfadasdasdf
      run: |
        echo ${{ steps.tejas.outputs.services }}
        echo ${{ steps.filter.outputs.changes }}
          
          
  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.services) }}
    steps:
      - name: sasdf
        run: echo "Building and testing${{ matrix.package }}"
        
