name: Build and Test Multiple Services

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse_json.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read and parse metadata.json
        id: parse_json
        run: |
          sudo apt-get install jq
          
          MATRIX=$(jq -c 'keys' metadata.json)

          # Print the matrix for debugging
          echo "Matrix: $MATRIX"

          # Set the matrix as an output
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT


  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{fromJson(needs.setup.outputs.matrix)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set service-specific parameters
        run: |
          echo "Service: ${{ matrix.service }}"
          echo $(jq '.["${{ matrix.service }}"].db_migration_dockerfile_path' metadata.json)"
