name: Build and Test Multiple Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    
  workflow_dispatch:

jobs:


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: sasdf
        run: echo ${{ github.event.head_commit.modified }}
        
      - name: Set service-specific parameters
        if: contains(join(github.event.head_commit.modified, ','), 'something/')
        run: echo "running 1"
