name: Schedule Job
run-name: Test ${{ github.event_name == 'schedule' && github.event.schedule == '*/10 * * * *' && 'stop' || 'default' }}

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Workflow Name
        run: |
          echo "Workflow name is: ${{ github.workflow }}"
      
      - name: Your job logic here
        run: |
          echo "Running the job logic..."
